---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserver
  namespace: hpa-test
spec:
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.2"
          requests:
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: hpa-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: echoserver

