apiVersion: v1
kind: Namespace
metadata:
  name: hpa-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserver
  namespace: hpa-test
spec:
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.2"
          requests:
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: hpa-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: echoserver
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-test
  namespace: hpa-test
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: echoserver
  targetCPUUtilizationPercentage: 60
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hey
  namespace: hpa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hey
  template:
    metadata:
      labels:
        app: hey
    spec:
      containers:
      - image: rcmorano/docker-hey
        imagePullPolicy: IfNotPresent
        name: hey
        command: ["hey"]
        args: ["-z", "1h", "-c", "100", "http://echoserver.hpa-test.svc.cluster.local"]

